# Use your custom image
onosnode[image]="kathara/onos-b5g"

# Forward the ONOS GUI port (8181) to your localhost
onosnode[bridged]=true
onosnode[port]="8181:8181/tcp"

# Connect the nodes to the same virtual wire
onosnode[0]="A"
switch[image]="kathara/sdn"
switch[0]="A"