# Use your custom image
onosnode[image]="kathara/onos-b5g"

# Forward the ONOS GUI port (8181) to your localhost
onosnode[bridged]=true
onosnode[port]="8181:8181/tcp"

# Control plane link: onosnode <-> both switches
onosnode[0]="A"
switch[image]="kathara/sdn"
switch[0]="A"
switch2[image]="kathara/sdn"
switch2[0]="A"

# Data plane links: switch <-> hosts
switch[1]="B"
switch[2]="C"
pc1[0]="B"
pc2[0]="C"

# Inter-switch link (linear topology)
switch[3]="D"
switch2[3]="D"

# Data plane links: switch2 <-> hosts
switch2[1]="E"
switch2[2]="F"
pc3[0]="E"
pc4[0]="F"